name = "kcumen-web-2026"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[vars]
RESEND_API_KEY = ""
EMAIL_FROM = "contacto@kcumen.co"
EMAIL_TO = "hola@kcumen.co"
